"""add last redir

Revision ID: 870c7f91a104
Revises: e0a9afb6003a
Create Date: 2026-03-14 18:40:21.038147

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '870c7f91a104'
down_revision: Union[str, Sequence[str], None] = 'e0a9afb6003a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('links', sa.Column('last_redirection', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('links', 'last_redirection')
    # ### end Alembic commands ###
