"""rename last_redir col

Revision ID: d2bbc9bbdd74
Revises: 870c7f91a104
Create Date: 2026-03-15 14:35:20.938585

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd2bbc9bbdd74'
down_revision: Union[str, Sequence[str], None] = '870c7f91a104'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('links', sa.Column('last_used_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.drop_column('links', 'last_redirection')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('links', sa.Column('last_redirection', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.drop_column('links', 'last_used_at')
    # ### end Alembic commands ###
