"""add index on last_used

Revision ID: ec90e3759a66
Revises: 3c022331929f
Create Date: 2026-03-16 02:12:01.778712

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec90e3759a66'
down_revision: Union[str, Sequence[str], None] = '3c022331929f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_links_last_used_at'), 'links', ['last_used_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_links_last_used_at'), table_name='links')
    # ### end Alembic commands ###
