from abc import ABC, abstractmethod
from datetime import datetime
from typing import Iterable

from app.links.models import Link


class AbstractLinkRepository(ABC):
    @abstractmethod
    async def get_by_id(self, id: int) -> Link | None: ...
    @abstractmethod
    async def get_by_long_url(self, long_url: str) -> Iterable[Link]: ...
    @abstractmethod
    async def get_by_slug(self, slug: str) -> Link | None: ...
    @abstractmethod
    async def create(self, link: Link) -> Link: ...
    @abstractmethod
    async def increment_redirects(self, slug: str, amount: int) -> None: ...
    @abstractmethod
    async def delete_by_slug(self, slug: str) -> Link: ...
    @abstractmethod
    async def update_long_url(self, slug: str, new_long_url: str) -> Link: ...
    @abstractmethod
    async def flush_unused_links(self, days: int) -> Iterable[str]: ...
    @abstractmethod
    async def update_stats(
        self, slug: str, redirects: int, last_used: datetime
    ) -> int: ...
