from abc import ABC
from typing import Iterable

from app.links.models import Link


class AbstractLinkRepository(ABC):
    async def get_by_id(self, id: int) -> Link | None: ...
    async def get_by_long_url(self, long_url: str) -> Iterable[Link]: ...
    async def get_by_slug(self, slug: str) -> Link | None: ...
    async def create(self, link: Link) -> Link: ...
    async def increment_redirects(self, slug: str) -> None: ...
